/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd.Customer;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mital
 */
public class OneTimePasswordJPanel extends javax.swing.JPanel {


    JPanel userProcessContainer;
    String otp;
    
    public OneTimePasswordJPanel(JPanel userProcessContainer, String otp) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.otp = otp;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        otpTextField = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        submitJButton.setBackground(new java.awt.Color(0, 153, 153));
        submitJButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("VALIDATE OTP");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton);
        submitJButton.setBounds(510, 280, 170, 23);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Your OTP");
        add(jLabel1);
        jLabel1.setBounds(430, 170, 120, 40);
        add(otpTextField);
        otpTextField.setBounds(570, 180, 190, 30);

        image.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        image.setForeground(new java.awt.Color(255, 255, 255));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("EMAIL VERIFICATION");
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(image);
        image.setBounds(410, 50, 380, 60);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("*Please check your email for OTP");
        add(jLabel2);
        jLabel2.setBounds(580, 220, 230, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-transparent-png (1).png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(390, 380, 440, 220);
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if(validateOtp(otp)) {
            JOptionPane.showMessageDialog(this, "Correct OTP");
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
            dwjp.validateOtp(true);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect OTP");
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            CustomerWorkAreaJPanel dwjp = (CustomerWorkAreaJPanel) component;
            dwjp.validateOtp(false);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private boolean validateOtp(String otp) {
        if(otpTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Otp cannot be empty");
        }
        if(otpTextField.getText().equals(otp)) {
            return true;
        } else {
            return false;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField otpTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
