/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd.NutritionistRole;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Enterprise.FoodWellnessEnterprise;
import Backend.Network.Network;
import Backend.Organization.OrganizationNutritionConsulatant;
import Backend.Organization.Organization;
import Backend.User.User;
import Backend.WorkQueue.NutritionistWorkRequest;
import FrontEnd.Customer.CustomerLoginWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mital
 */
public class NutritionistRequestJPanel extends javax.swing.JPanel {

 
     private JPanel userProcessContainer;
    private Enterprise enterprise;
    private User userAccount;
    private EcoSystem system;
    private Network sourceNetwork;
    private Network targetNetwork;
    
    public NutritionistRequestJPanel(JPanel userProcessContainer, User account, Enterprise enterprise, EcoSystem system, Network sourceNetwork, Network targetNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.sourceNetwork = sourceNetwork;
        this.targetNetwork = targetNetwork;
        if(null != enterprise) {
            valueLabel.setText(enterprise.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        enterprice = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        messagejLabel = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        RequestjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(0, 102, 102));
        backJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        enterprice.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        enterprice.setForeground(new java.awt.Color(0, 153, 153));
        enterprice.setText("Enterprise: ");
        add(enterprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        valueLabel.setForeground(new java.awt.Color(0, 153, 153));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 50, -1));

        messagejLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        messagejLabel.setForeground(new java.awt.Color(255, 255, 255));
        messagejLabel.setText("Appointment Details");
        add(messagejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 210, 30));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 310, 30));

        RequestjButton.setBackground(new java.awt.Color(0, 153, 153));
        RequestjButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        RequestjButton.setForeground(new java.awt.Color(255, 255, 255));
        RequestjButton.setText("Book Appointment");
        RequestjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        RequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestjButtonActionPerformed(evt);
            }
        });
        add(RequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-transparent-png (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 410, 220));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Physician Appointment Booking");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 370, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void RequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestjButtonActionPerformed
        // TODO add your handling code here:
         String message = messageJTextField.getText();
        if (!message.isEmpty()) {
            NutritionistWorkRequest request = new NutritionistWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");

            Organization org = null;
            Enterprise ent = null;
            if (sourceNetwork != targetNetwork) {
                for (Enterprise enterprise : targetNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof FoodWellnessEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof OrganizationNutritionConsulatant) {
                            org = organization;
                            break;
                        }
                    }
                }
            } else {
                for (Enterprise enterprise : sourceNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof FoodWellnessEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof OrganizationNutritionConsulatant) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct input");
        }
        messageJTextField.setText("");

    }//GEN-LAST:event_RequestjButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        CustomerLoginWorkAreaJPanel clwjp = (CustomerLoginWorkAreaJPanel) component;
        clwjp.populateRequestTable(sourceNetwork);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequestjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JLabel messagejLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
