/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd.BeauticianRole;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Enterprise.BodycareWellnessEnterprise;
import Backend.Network.Network;
import Backend.Organization.Organization;
import Backend.Organization.OrganizationBeautySalon;
import Backend.User.User;
import Backend.WorkQueue.BeauticianWorkRequest;
import FrontEnd.Customer.CustomerLoginWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Aashay
 */
public class RequestSalonJPanel extends javax.swing.JPanel {

  
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private User userAccount;
    private EcoSystem system;
    private Network sourceNetwork;
    private Network targetNetwork;
    
    public RequestSalonJPanel(JPanel userProcessContainer, User account, Enterprise enterprise, EcoSystem system, Network sourceNetwork, Network targetNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        this.sourceNetwork = sourceNetwork;
        this.targetNetwork = targetNetwork;
        if(null != enterprise) {
            valueLabel.setText(enterprise.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        enterprice = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        messagejLabel = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        RequetsjButton = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(0, 102, 102));
        backJButton.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.setBorder(null);
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        enterprice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        enterprice.setForeground(new java.awt.Color(0, 153, 153));
        enterprice.setText(" Enterprise: ");
        add(enterprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 110, 40));

        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 190, 40));

        messagejLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        messagejLabel.setForeground(new java.awt.Color(255, 255, 255));
        messagejLabel.setText("Appointment Details");
        add(messagejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 200, 40));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 290, 40));

        RequetsjButton.setBackground(new java.awt.Color(0, 153, 153));
        RequetsjButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        RequetsjButton.setForeground(new java.awt.Color(255, 255, 255));
        RequetsjButton.setText("Book Appointment");
        RequetsjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        RequetsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequetsjButtonActionPerformed(evt);
            }
        });
        add(RequetsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 190, 40));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-transparent-png (1).png"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 400, 210));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hair Salon Appointment Booking");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 370, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerLoginWorkAreaJPanel clwjp = (CustomerLoginWorkAreaJPanel) component;
        clwjp.populateRequestTable(sourceNetwork);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void RequetsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequetsjButtonActionPerformed
        // TODO add your handling code here:
        String message = messageJTextField.getText();
        if (!message.isEmpty()) {
            BeauticianWorkRequest request = new BeauticianWorkRequest();
            request.setMessage(message);
            request.setSender(userAccount);
            request.setStatus("Sent");

            Organization org = null;
            Enterprise ent = null;
            if (sourceNetwork != targetNetwork) {
                for (Enterprise enterprise : targetNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof BodycareWellnessEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof OrganizationBeautySalon) {
                            org = organization;
                            break;
                        }
                    }
                }
            } else {
                for (Enterprise enterprise : sourceNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof BodycareWellnessEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof OrganizationBeautySalon) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct input");
        }
        messageJTextField.setText("");
    }//GEN-LAST:event_RequetsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RequetsjButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterprice;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JLabel messagejLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
